---

resources:
  - name: git-repository
    type: git
    source:
      uri: https://github.com/Godfather27/concourse-testapp.git
      branch: master

jobs:
  - name: lint
    plan:
      - get: git-repository
        trigger: true
      - task: lint
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: ruby, tag: '2.5'}

          inputs:
            - name: git-repository

          run:
            path: sh
            dir: git-repository
            args: ["./bin/rubocop.sh"]

  - name: unit-tests
    plan:
      - get: git-repository
        trigger: true
      - task: unit-tests
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: ruby, tag: '2.5'}

          inputs:
            - name: git-repository

          run:
            path: sh
            dir: git-repository
            args: ["./bin/unit-tests.sh"]

  - name: security-scan
    plan:
      - get: git-repository
        trigger: true
      - task: security-scan
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: ruby, tag: '2.5'}

          inputs:
            - name: git-repository

          run:
            path: sh
            dir: git-repository
            args: ["./bin/security-scan.sh"]

  - name: dependency-check
    plan:
      - get: git-repository
        trigger: true
      - task: dependency-check
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: ruby, tag: '2.5'}

          inputs:
            - name: git-repository

          run:
            path: sh
            dir: git-repository
            args: ["./bin/dependency-check.sh"]

  - name: acceptance-tests
    plan:
      - get: git-repository
        passed: [dependency-check, security-scan, unit-tests, lint]
        trigger: true
      - task: acceptance-tests
        config:
          platform: linux

          image_resource:
            type: docker-image
            source: {repository: ruby, tag: '2.5'}

          inputs:
            - name: git-repository

          run:
            path: sh
            dir: git-repository
            args: ["./bin/acceptance-tests.sh"]

  - name: deploy
    plan:
      - get: git-repository
        passed: [acceptance-tests]
        trigger: true
      - task: deploy
        config:
          platform: linux

          image_resource:
            type: docker-image
            source:
              repository: concourse/bosh-cli

          inputs:
            - name: git-repository

          run:
            path: echo
            args:
              - 'deploys the app'
